#!/usr/bin/env bash
# Installs, configures, and starts the server

sudo apt-get -y update;
sudo apt-get -y install nginx;
sudo ufw allow 'Nginx HTTP';
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';
THESERVER_CONF=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
        
        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

}"

bash -c "echo -e '$THESERVER_CONF' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
