#!/usr/bin/env bash
# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -z "$pid" ]; then
    echo "Process 4-to_infinity_and_beyond not found."
else
    # Send a termination signal to the process
    kill "$pid"
fi
