#!/usr/bin/env bash
# Find the PID of the 7-highlander process
pid=$(pgrep -o -f "7-highlander")

if [ -z "$pid" ]; then
    echo "Process 7-highlander not found."
else
    # Send a termination signal to the process group
    echo "Terminating process $pid"
    pkill -P "$pid"
fi
