#!/usr/bin/env bash
# ThiscriptSHOW usr,usrID,&homedir path for each user in /etc/passwd
while IFS=':' read -r username _ uid _ _ home_dir _; do
    echo "$username:$uid:$home_dir"
done < /etc/passwd
