#!/usr/bin/env bash
# This script displays "Best School" 10 times, and on the 9th iteration, it says "Hi" on a new line
i=0
while ((i <= 9)); do
    if [ "$i" -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
