#!/usr/bin/env bash
# This scriptdisplay"BestSchool"10x&on9thiteration,itsays"Hi"o newline
i=0
while ((i <= 10)); do
    if [ "$i" -eq 9 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
