#!/usr/bin/env bash
# This script displays all the content of a directory in a list format
for file in *; do
    if [[ ! $file =~ ^\..* ]]; then
        filename="${file#*-}";
        echo "$filename"
    fi
done
