#!/usr/bin/env bash
# for firewall set up itinstall ufw and enable ports 22, 443, 8080

# Update package lists
sudo apt-get update

# Install UFW
sudo apt-get install -y ufw

# Set default policies to block incoming and allow outgoing traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (port 22)
sudo ufw allow 22

# Allow HTTPS (port 443)
sudo ufw allow 443

# Allow HTTP (port 80)
sudo ufw allow 80

# Enable UFW
sudo ufw -y enable
~                                                                                  
~                                                                                  
~                                                                                  
~                                                                                  
~                                                                                  
~          
