#!/usr/bin/env bash
# solve the container error using the command b
# Run apache on container
#!/usr/bin/env bash
# solve the container error
sudo vim /etc/apache2/sites-available/httpd.conf
sudo a2ensite httpd.conf
sudo httpd.conf configtest
sudo service apache2 start
